### ISSUE TITLE
Trouble installing in python 3.5.3 on Raspberry Pi 3B+ using Raspbian Stretch and pip3

### ISSUE THREAD

**Issue by morabrandoi** [azzra/python3-wiimote#7]
I have already run
`sudo apt-get install libcwiid1`
and
`sudo apt-get install libcwiid1-dev`

Which manages to install cwiid for Python 2 on my Pi.
So to install it for Python 3 I did
`sudo pip3 install cwiid`
and this is the console output:
```

Collecting cwiid
  Downloading https://files.pythonhosted.org/packages/fa/e8/d0f03c60bbdc583a7fa37a126e9b20055fb3752861820c25bd212dc62756/cwiid-3.0.0.tar.gz
Building wheels for collected packages: cwiid
  Running setup.py bdist_wheel for cwiid ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-awriumlk/cwiid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmphrh6qfp3pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'cwiid' extension
  creating build
  creating build/temp.linux-armv7l-3.5
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c cwiidmodule.c -o build/temp.linux-armv7l-3.5/cwiidmodule.o
  cwiidmodule.c: In function ‘PyInit_cwiid’:
  cwiidmodule.c:157:3: warning: ‘return’ with no value, in function returning non-void
     return;
     ^~~~~~
  cwiidmodule.c:150:16: note: declared here
   PyMODINIT_FUNC PyInit_cwiid(void)
                  ^~~~~~~~~~~~
  cwiidmodule.c:176:3: warning: ‘return’ with no value, in function returning non-void
     return;
     ^~~~~~
  cwiidmodule.c:150:16: note: declared here
   PyMODINIT_FUNC PyInit_cwiid(void)
                  ^~~~~~~~~~~~
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c Wiimote.c -o build/temp.linux-armv7l-3.5/Wiimote.o
  Wiimote.c: In function ‘Wiimote_get_state’:
  Wiimote.c:563:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                     state.ext.motionplus.low_speed[CWIID_PHI],
                                                         ^
  Wiimote.c:564:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                     state.ext.motionplus.low_speed[CWIID_THETA],
                                                         ^
  Wiimote.c:565:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                     state.ext.motionplus.low_speed[CWIID_PSI]);
                                                         ^
  Wiimote.c: In function ‘ConvertMesgArray’:
  Wiimote.c:1009:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                       mesg[i].motionplus_mesg.low_speed[CWIID_PHI],
                                                              ^
  Wiimote.c:1010:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                       mesg[i].motionplus_mesg.low_speed[CWIID_THETA],
                                                              ^
  Wiimote.c:1011:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                       mesg[i].motionplus_mesg.low_speed[CWIID_PSI]);
                                                              ^
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cwiid
  Running setup.py clean for cwiid
Failed to build cwiid
Installing collected packages: cwiid
  Running setup.py install for cwiid ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-awriumlk/cwiid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mjs2n7pp-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'cwiid' extension
    creating build
    creating build/temp.linux-armv7l-3.5
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c cwiidmodule.c -o build/temp.linux-armv7l-3.5/cwiidmodule.o
    cwiidmodule.c: In function ‘PyInit_cwiid’:
    cwiidmodule.c:157:3: warning: ‘return’ with no value, in function returning non-void
       return;
       ^~~~~~
    cwiidmodule.c:150:16: note: declared here
     PyMODINIT_FUNC PyInit_cwiid(void)
                    ^~~~~~~~~~~~
    cwiidmodule.c:176:3: warning: ‘return’ with no value, in function returning non-void
       return;
       ^~~~~~
    cwiidmodule.c:150:16: note: declared here
     PyMODINIT_FUNC PyInit_cwiid(void)
                    ^~~~~~~~~~~~
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c Wiimote.c -o build/temp.linux-armv7l-3.5/Wiimote.o
    Wiimote.c: In function ‘Wiimote_get_state’:
    Wiimote.c:563:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                       state.ext.motionplus.low_speed[CWIID_PHI],
                                                           ^
    Wiimote.c:564:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                       state.ext.motionplus.low_speed[CWIID_THETA],
                                                           ^
    Wiimote.c:565:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                       state.ext.motionplus.low_speed[CWIID_PSI]);
                                                           ^
    Wiimote.c: In function ‘ConvertMesgArray’:
    Wiimote.c:1009:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                         mesg[i].motionplus_mesg.low_speed[CWIID_PHI],
                                                                ^
    Wiimote.c:1010:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                         mesg[i].motionplus_mesg.low_speed[CWIID_THETA],
                                                                ^
    Wiimote.c:1011:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                         mesg[i].motionplus_mesg.low_speed[CWIID_PSI]);
                                                                ^
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-awriumlk/cwiid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mjs2n7pp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-awriumlk/cwiid/

```

Help would be very much appreciated.
Thank you!

**Comment by jgeudens** [comment]
I had the same issue on rpi0w and my Ubuntu desktop. The error message mentions that a function just uses return instead of return xx. 

I fixed this by changing lines 157 and 176 in cwiidmodule.c from `return` to `return NULL`.
I then compiled the library and extension on my pi following the README and it worked.

I created a pull request with the fix.

**Comment by azzra** [comment]
closed by #8, thanks to @morabrandoi & @jgeudens

**Comment by thk** [comment]
Hello,
i just stumbled upon the same error when installing `cwiid` using pip/pypi. Will you update the project with a version, where the above error is fixed? The pypi-project-page refers to a release from Apr 28, 2017.
Thx!

**Comment by GCMan777** [comment]
when i try

> sudo pip3 install cwiid

i get

> Collecting cwiid
  Downloading https://files.pythonhosted.org/packages/fa/e8/d0f03c60bbdc583a7fa37a126e9b20055fb3752861820c25bd212dc62756/cwiid-3.0.0.tar.gz
Building wheels for collected packages: cwiid
  Running setup.py bdist_wheel for cwiid ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bx0dhl_m/cwiid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpa2d4ju3gpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'cwiid' extension
  creating build
  creating build/temp.linux-armv7l-3.5
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c cwiidmodule.c -o build/temp.linux-armv7l-3.5/cwiidmodule.o
  cwiidmodule.c:27:19: fatal error: cwiid.h: No such file or directory
   #include <cwiid.h>
                     ^
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
>  Failed building wheel for cwiid
  Running setup.py clean for cwiid
Failed to build cwiid
Installing collected packages: cwiid
  Running setup.py install for cwiid ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bx0dhl_m/cwiid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-omfholw_-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'cwiid' extension
    creating build
    creating build/temp.linux-armv7l-3.5
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c cwiidmodule.c -o build/temp.linux-armv7l-3.5/cwiidmodule.o
    cwiidmodule.c:27:19: fatal error: cwiid.h: No such file or directory
     #include <cwiid.h>
                       ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
>Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bx0dhl_m/cwiid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-omfholw_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-bx0dhl_m/cwiid/

**Comment by ArchiPi** [comment]
> I had the same issue on rpi0w and my Ubuntu desktop. The error message mentions that a function just uses return instead of return xx.
> 
> I fixed this by changing lines 157 and 176 in cwiidmodule.c from `return` to `return NULL`.
> I then compiled the library and extension on my pi following the README and it worked.
> 
> I created a pull request with the fix.

It seems like you solved the problem! Could you explain how to get it to work for beginners? I'm not sure how to implement the changes and I still get the original error @jgeudens

**Comment by Bibo-Joshi** [comment]
> Hello,
> i just stumbled upon the same error when installing `cwiid` using pip/pypi. Will you update the project with a version, where the above error is fixed? The pypi-project-page refers to a release from Apr 28, 2017.
> Thx!

@azzra I'm having trouble installing, too and would be glad to see a new release on PyPi :)

**Comment by TwizzyDizzy** [comment]
**Disclaimer**: running this on Raspberry Pi 2B on Raspbian Buster and Python 3.7.3

That's (probably) got nothing to do with a new release on PyPi.

Just installed from master of this repo:

```
wget https://github.com/azzra/python3-wiimote/tarball/master
tar xfz master
cd azzra-python3-wiimote-d1f387c/python
pip install .
```

... and still get those errors:

```
(virtualenv) root@raspberrypi:/opt/virtualenv/azzra-python3-wiimote-d1f387c/python# pip install .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /opt/virtualenv/azzra-python3-wiimote-d1f387c/python
Building wheels for collected packages: cwiid
  Running setup.py bdist_wheel for cwiid ... error
  Complete output from command /opt/virtualenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-8x7oty94/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-fjvfyfpe --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building 'cwiid' extension
  creating build
  creating build/temp.linux-armv7l-3.7
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/virtualenv/include -I/usr/include/python3.7m -c cwiidmodule.c -o build/temp.linux-armv7l-3.7/cwiidmodule.o
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/virtualenv/include -I/usr/include/python3.7m -c Wiimote.c -o build/temp.linux-armv7l-3.7/Wiimote.o
  Wiimote.c: In function ‘Wiimote_get_state’:
  Wiimote.c:568:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                     state.ext.motionplus.low_speed[CWIID_PHI],
                                                         ^
  Wiimote.c:569:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                     state.ext.motionplus.low_speed[CWIID_THETA],
                                                         ^
  Wiimote.c:570:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                     state.ext.motionplus.low_speed[CWIID_PSI]);
                                                         ^
  Wiimote.c: In function ‘Wiimote_read’:
  Wiimote.c:804:2: warning: ‘PyObject_AsWriteBuffer’ is deprecated [-Wdeprecated-declarations]
    if (PyObject_AsWriteBuffer(pyRetBuf, &buf, &len)) {
    ^~
  In file included from /usr/include/python3.7m/Python.h:147,
                   from Wiimote.c:23:
  /usr/include/python3.7m/abstract.h:500:17: note: declared here
   PyAPI_FUNC(int) PyObject_AsWriteBuffer(PyObject *obj,
                   ^~~~~~~~~~~~~~~~~~~~~~
  Wiimote.c: In function ‘ConvertMesgArray’:
  Wiimote.c:1014:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                       mesg[i].motionplus_mesg.low_speed[CWIID_PHI],
                                                              ^
  Wiimote.c:1015:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                       mesg[i].motionplus_mesg.low_speed[CWIID_THETA],
                                                              ^
  Wiimote.c:1016:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                       mesg[i].motionplus_mesg.low_speed[CWIID_PSI]);
                                                              ^
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cwiid
  Running setup.py clean for cwiid
Failed to build cwiid
Installing collected packages: cwiid
  Running setup.py install for cwiid ... error
    Complete output from command /opt/virtualenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-8x7oty94/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xkbv3bod/install-record.txt --single-version-externally-managed --compile --install-headers /opt/virtualenv/include/site/python3.7/cwiid:
    running install
    running build
    running build_ext
    building 'cwiid' extension
    creating build
    creating build/temp.linux-armv7l-3.7
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/virtualenv/include -I/usr/include/python3.7m -c cwiidmodule.c -o build/temp.linux-armv7l-3.7/cwiidmodule.o
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/virtualenv/include -I/usr/include/python3.7m -c Wiimote.c -o build/temp.linux-armv7l-3.7/Wiimote.o
    Wiimote.c: In function ‘Wiimote_get_state’:
    Wiimote.c:568:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                       state.ext.motionplus.low_speed[CWIID_PHI],
                                                           ^
    Wiimote.c:569:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                       state.ext.motionplus.low_speed[CWIID_THETA],
                                                           ^
    Wiimote.c:570:55: error: ‘struct motionplus_state’ has no member named ‘low_speed’
                                       state.ext.motionplus.low_speed[CWIID_PSI]);
                                                           ^
    Wiimote.c: In function ‘Wiimote_read’:
    Wiimote.c:804:2: warning: ‘PyObject_AsWriteBuffer’ is deprecated [-Wdeprecated-declarations]
      if (PyObject_AsWriteBuffer(pyRetBuf, &buf, &len)) {
      ^~
    In file included from /usr/include/python3.7m/Python.h:147,
                     from Wiimote.c:23:
    /usr/include/python3.7m/abstract.h:500:17: note: declared here
     PyAPI_FUNC(int) PyObject_AsWriteBuffer(PyObject *obj,
                     ^~~~~~~~~~~~~~~~~~~~~~
    Wiimote.c: In function ‘ConvertMesgArray’:
    Wiimote.c:1014:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                         mesg[i].motionplus_mesg.low_speed[CWIID_PHI],
                                                                ^
    Wiimote.c:1015:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                         mesg[i].motionplus_mesg.low_speed[CWIID_THETA],
                                                                ^
    Wiimote.c:1016:60: error: ‘struct cwiid_motionplus_mesg’ has no member named ‘low_speed’
                                         mesg[i].motionplus_mesg.low_speed[CWIID_PSI]);
                                                                ^
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/opt/virtualenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-8x7oty94/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xkbv3bod/install-record.txt --single-version-externally-managed --compile --install-headers /opt/virtualenv/include/site/python3.7/cwiid" failed with error code 1 in /tmp/pip-req-build-8x7oty94/
```

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Ok... now... this seems a bit ludacris... BUT... with barely any knowledge of C I managed to fix the error above. A word of caution: I do not fully understand what I did there and I do not know what the implications of my changes are.

I have basic programming knowledge so I started from

`"error: ‘struct motionplus_state’ has no member named ‘low_speed’"`

OK.. seems like "somebody" wants a `low_speed` where there is none. So I simply removed it. My **GUESS** is... that the python binding refers to something in `libcwiid` which is not there anymore OR not yet.

Here's a `git diff` you can use to `git apply` to `master` (which is `d1f387c613181b4a2a4444aba9692c2164de9aea`):

```
diff --git a/python/Wiimote.c b/python/Wiimote.c
index 6d18891..0780ec0 100644
--- a/python/Wiimote.c
+++ b/python/Wiimote.c
@@ -559,15 +559,11 @@ static PyObject *Wiimote_get_state(Wiimote* self, void *closure)
                break;
        case CWIID_EXT_MOTIONPLUS:
                if (state.rpt_mode & CWIID_RPT_MOTIONPLUS) {
-                       PyExt = Py_BuildValue("{s:(I,I,I),s:(I,I,I)}",
+                       PyExt = Py_BuildValue("{s:(I,I,I)}",
                                          "angle_rate",
                                   state.ext.motionplus.angle_rate[CWIID_PHI],
                                   state.ext.motionplus.angle_rate[CWIID_THETA],
-                                  state.ext.motionplus.angle_rate[CWIID_PSI],
-                                  "low_speed",
-                                  state.ext.motionplus.low_speed[CWIID_PHI],
-                                  state.ext.motionplus.low_speed[CWIID_THETA],
-                                  state.ext.motionplus.low_speed[CWIID_PSI]);
+                                  state.ext.motionplus.angle_rate[CWIID_PSI]);
 
                        if (!PyExt) {
                                Py_DECREF(PyState);
@@ -1005,15 +1001,11 @@ PyObject *ConvertMesgArray(int mesg_count, union cwiid_mesg mesg[])
                                       mesg[i].balance_mesg.left_bottom);
                        break;
                case CWIID_MESG_MOTIONPLUS:
-                       mesgVal = Py_BuildValue("{s:(I,I,I),s:(I,I,I)}",
+                       mesgVal = Py_BuildValue("{s:(I,I,I)}",
                                                "angle_rate",
                                     mesg[i].motionplus_mesg.angle_rate[CWIID_PHI],
                                     mesg[i].motionplus_mesg.angle_rate[CWIID_THETA],
-                                    mesg[i].motionplus_mesg.angle_rate[CWIID_PSI],
-                                    "low_speed",
-                                    mesg[i].motionplus_mesg.low_speed[CWIID_PHI],
-                                    mesg[i].motionplus_mesg.low_speed[CWIID_THETA],
-                                    mesg[i].motionplus_mesg.low_speed[CWIID_PSI]);
+                                    mesg[i].motionplus_mesg.angle_rate[CWIID_PSI]);
                                     
                        break;
                case CWIID_MESG_ERROR:
```

The only thing I know is: I am now at least able to install `cwiid`:

```
(virtualenv) root@raspberrypi:/opt/virtualenv/azzra-python3-wiimote-d1f387c/python# pip install .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /opt/virtualenv/azzra-python3-wiimote-d1f387c/python
Building wheels for collected packages: cwiid
  Running setup.py bdist_wheel for cwiid ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-7v6tepea/wheels/8a/ca/5d/56e78f187bcd5471ca252e24e49386a09b952b00c158ea30f3
Successfully built cwiid
Installing collected packages: cwiid
Successfully installed cwiid-3.0.0
```

Cheers
Thomas
